server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: burning91
        driver-class-name: org.postgresql.Driver
    sql:
        init:
            mode: always #Always will run the base sql codes
